### ISSUE TITLE
Need a way to visualize greenspaces already delineated

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/urban_greenspaces#3]
This will be more important once we try to open this up more widely and let people contribute greenspaces they are interested in (which will probably entail creating a separate repo).

But, @johnWilshire any ideas on how to visualize all greenspaces at once, in their separate .geojson files?

Maybe [this](https://github.com/mapbox/geojson-merge) will be helpful?

**Comment by johnWilshire** [comment]
http://dropchop.io/

works amazingly!

jsut go upload files from your computer and select all greenspaces, this shoud work in the short term I would imagine

**Comment by johnWilshire** [comment]
@coreytcallaghan 

I also think that perhaps we should  rename our greenspace filename/id structure?


<3 letter country code>-<state/prov>-<park_name>.geojson
so they make more sense when grouped alphabetically?

if you agree I can do this using linux so dont worry about manually doing it

additionally I renamed the base folder to have underscores instead of spaces
